# cache components
# before_install
# install to install the dependencies
# before_script
# script  to build the project
# before_cache
# after_success
# after_failure
# before_deploy
# deploy
# after_deploy
# after_script
language: node_js
node_js:
  - node

script:
  - npm install
  - npm run build

deploy:
  provider: s3
  bucket: "hadeeth-pro-ui"
  skip_cleanup: true
  local_dir: build
  on:
    branch: master


